### ISSUE TITLE
Saving credentials fails if ${env:\userprofile}\.Atlassian.Bitbucket directory doesn't exist

### ISSUE THREAD

**Issue by tet3** [beyondcomputing-org/Atlassian.Bitbucket#1]
PowerShell Core 6 on Windows 10. When trying to invoke `Login-Bitbucket -Save -AtlassianCredential $Cred -OAuthConsumer $OAuth` or just `Save-BitbucketLogin` after doing the OAuth login without saving, the following errors are thrown: 
```
New-Item : Cannot find a provider with the name '[BitbucketSettings]'.
At C:\Users\thomas.taylor\Documents\PowerShell\Modules\Atlassian.Bitbucket\0.15.1\Classes\Atlassian.Bitbucket.Auth.psm1:136 char:13
+             New-Item -Type Directory -Path [BitbucketSettings]::SAVE_ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: ([BitbucketSettings]:String) [New-Item], ProviderNotFoundException
+ FullyQualifiedErrorId : ProviderNotFound,Microsoft.PowerShell.Commands.NewItemCommand

Export-CliXml : Could not find a part of the path 'C:\Users\thomas.taylor\.Atlassian.Bitbucket\BitbucketAuth.xml'.
At C:\Users\thomas.taylor\Documents\PowerShell\Modules\Atlassian.Bitbucket\0.15.1\Classes\Atlassian.Bitbucket.Auth.psm1:149 char:17
+ ...     $Save | Export-CliXml -Path ([BitbucketSettings]::SAVE_PATH)  -En ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OpenError: (:) [Export-Clixml], DirectoryNotFoundException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ExportClixmlCommand
```

I'm not sure what's going on with the first one, since the second one clearly shows that it's able to figure out the desired `$SAVE_PATH`. But once I created the `.Atlassian.Bitbucket` folder, then the `Save-BitbucketLogin` cmdlet ran without complaint, and the XML file is there.

**Comment by eelkram** [comment]
Thanks for the report @tet3.  I've fixed the issue and published a new version to the gallery 0.15.2.  Let me know if you have any issues.  It was just missing a set of parens around the variable in the create directory call.  

I need to add some better testing around the profile functionality but the way I originally wrote it doesn't lend itself to easily being tested.  I'll probably look at restructuring the code so I can add a bunch of test coverage to that functionality.
