### ISSUE TITLE
Cloning URL from repository object 

### ISSUE THREAD

**Issue by yellappam** [beyondcomputing-org/Atlassian.Bitbucket#10]
I have a requirement to clone all the repositories in a given project. I can get list of repositories with below two steps and the next step is to clone them.

1. Login-Bitbucket
2. Get-BitbucketRepository

Currently, I get the repository name and preparing the cloning the URL manually. It would be nice to provide HTTPS and SSH cloning URLs properties in the PSCustomObject return by Get-BitbucketRepository function. Please suggest if this has already been done in other function.

**Comment by markphelan** [comment]
@yellappam For each repository returned by Get-BitbucketRepository you can use `$repo`.`links`.`clone` to obtain both https and ssh URLs for a repo.
