### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by moretti-zenfolio** [beyondcomputing-org/Atlassian.Bitbucket#13]
Hi
```
PS C:\WINDOWS\system32> Login-Bitbucket

cmdlet New-BitbucketLogin at command pipeline position 1
Supply values for the following parameters:
Credential
Welcome Maximiliano Moretti
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Atlassian.Bitbucket\0.28.0\Atlassian.Bitbucket.Authentication.psm1:196 char:9
+         $Team = $Teams[$index].username
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

I created the app password and I added all the permissions

**Comment by eelkram** [comment]
Interesting.. it looks like it is getting some details but not able to get details on the team that you are a part of.  However, Atlassian is deprecating those endpoints with all the authentication changes they have been working on.  So I'll be needing to update this to use the new endpoints which hopefully will address any issues.

https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/

**Comment by eelkram** [comment]
The module has been updated to 0.29.0 which moves all the related endpoints over to the new workspaces.  Please let me know if you still have an issue.

**Comment by eelkram** [comment]
Closing this issue after the authentication updates in preparation for the deprecated API endpoints.
