### ISSUE TITLE
Authentication validation error without read rights on /user/ 

### ISSUE THREAD

**Issue by sipho102** [beyondcomputing-org/Atlassian.Bitbucket#6]
First off thank you for the module I am using it to automate tasks a lot but have encountered an issue id like to report.

### The issue
Due to 2FA the normal login process of the module did no longer work. This should be alleviated by the app passwords by atlassian which allow for authentication via basic user:pw in the authorization header. (see https://bitbucket.org/blog/app-passwords-bitbucket-cloud)
This would work perfectly fine with this module with one exception: If the the app password is set up without read rights on the /user/ endpoint. The login then fails due to the **ValidateLoginAndSaveUser** as it calls the endpoint to validate the login.

### How to re-create:
- Create a app password in your bitbucket.org account with NO rights on the account information
- Run a Login-Bitbucket -Credential $your_app_password_creds
This will give you the error 'Login Failed - credentials are invalid.  Use Login-Bitbucket to re-authenticate.' as designed.

### Suggestions/Ideas for a Solution
- Maybe just add a cmdlet switch -SkipValidation to the Login-Bitbucket cmdlet and use it in the instatiatin of the [BitbucketAuth] object? 
- Use another way to validate the login
- Just document that the read right on the /user/ endpoint must be enabled for app passwords

**Comment by eelkram** [comment]
Hi @sipho102 ,

Great and thanks for the report.  I think your suggestions are spot on and would probably do both #1 allow a -SkipValidation option and #3 update the documentation about the required permissions.  I should have some time this weekend to address these items unless you are interested in submitting a PR with the changes.  A PR would be very welcome!

Thanks,
Mark

**Comment by eelkram** [comment]
I've updated the readme to call out app passwords and needed permissions.  I'm going to close this issue.  If you want to add a -SkipValidation option in the future feel free to submit a PR.
