### ISSUE TITLE
Login-Bitbucket command always fails

### ISSUE THREAD

**Issue by aaronbauman** [beyondcomputing-org/Atlassian.Bitbucket#7]
OSX 10.15.3
Powershell 7.0.4
Atlassian.Bitbucket 0.24.1

Get this error every time I run `Login-Bitbucket`.
Confirmed I'm using the correct password.
```
Exception: /Users/bauman/.local/share/powershell/Modules/Atlassian.Bitbucket/0.24.1/Classes/Atlassian.Bitbucket.Auth.psm1:77
Line |
  77 |              throw 'Login Failed - credentials are invalid.  Use Login …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Login Failed - credentials are invalid.  Use Login-Bitbucket to re-authenticate.

```

OAuth login works ok.

**Comment by eelkram** [comment]
Hi @aaronbauman,

What were you using for the password in this scenario?  Were you using an app password or a regular password?  If you are using an a regular password can you try creating an app password and see if that works?

I was using the module today without issue, but I always use app passwords.

Thanks,
Mark

**Comment by Ayanmullick** [comment]
`Login-Bitbucket` fails for me, even with an App password.

```
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Atlassian.Bitbucket\0.27.0\Atlassian.Bitbucket.Authentication.psm1:196 char:9
+         $Team = $Teams[$index].username
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
```

**Comment by eelkram** [comment]
@Ayanmullick The module needs to send request to a specific team so during login it grabs your team membership information and prompts you to select which team you would like to default to.  Based on where it failed, it appears that you got no team membership information back from Bitbucket.  Assuming Bitbucket hasn't changed something and now allows you to not be a member of a team it is probably a permission issue.  I haven't tested it for a while, but you need to grant you app password access to a few things.  As per the readme, "read access to the account and workspace membership".  Feel free to submit a PR to improve the error handling or logic on this.

I'm going to close this issue as the original requester @aaronbauman hasn't responded.
