### ISSUE TITLE
Looking for a standalone pipelines report

### ISSUE THREAD

**Issue by aaronbauman** [beyondcomputing-org/Atlassian.Bitbucket#8]
I like the format of the HTML deployment report, but would like to report on pipelines for all the projects in my workspace.

Would it be feasible to add such a feature inside this project, or would you recommend doing it in a new project?

**Comment by eelkram** [comment]
Hi @aaronbauman,

The cmdlet Get-BitbucketProjectDeploymentReport isn't actually tied to a specific project in Bitbucket, probably bad naming on my part...  You can pass in whatever repos you want to the report so you can do every repo in your account if you like assuming they are in the same team.  If they are in different teams you could use the json return type and combine the results from multiple teams before passing to Get-BitbucketProjectDeploymentReportHTML which is a private function that would generate the report.  If that is a use case you have I could make that function public in an updated version.

Let me know.

Thanks,
Mark
